import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '@/constants/Colors';
import { Layout } from '@/constants/Layout';
const THEME_GREEN = '#0B5C36';
const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 48) / 2;
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F6F8F7",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Layout.spacing.lg,
    paddingVertical: 15,
    backgroundColor: Colors.primary,
  },
  headerEyebrow: {
    fontSize: 11,
    color: "rgba(255,255,255,0.78)",
    textTransform: "uppercase",
    fontWeight: "800",
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "900",
    color: "#FFF",
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    padding: Layout.screenPadding,
    alignSelf: "center",
    width: "100%",
    maxWidth: Layout.contentMaxWidth,
  },
  errorText: {
    marginBottom: 14,
    padding: 10,
    borderRadius: 10,
    backgroundColor: "#FFF4F4",
    color: Colors.tertiary,
    borderWidth: 1,
    borderColor: "#FECACA",
    fontSize: 12,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
  },
  statLabel: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 17,
    fontWeight: "800",
    color: Colors.text,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  actionButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  actionButtonAlt: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  actionButtonText: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "800",
  },
  actionButtonTextAlt: {
    color: Colors.primary,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: Colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: "#E8F5E9",
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.textSecondary,
  },
  tabLabelActive: {
    color: Colors.primary,
  },
  panel: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
    ...Layout.cardShadow,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 12,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 6,
  },
  panelSubtitle: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 17,
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 6,
    marginTop: 12,
  },
  inputBox: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
  },
  inputError: {
    borderColor: Colors.tertiary,
  },
  input: {
    fontSize: 14,
    color: Colors.text,
    padding: 0,
  },
  textArea: {
    minHeight: 76,
    paddingTop: 10,
    paddingBottom: 10,
  },
  multiLineInput: {
    textAlignVertical: "top",
    minHeight: 56,
  },
  row: {
    flexDirection: Layout.isSmallDevice ? "column" : "row",
    gap: 10,
  },
  flexHalf: {
    flex: 1,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  horizontalChips: {
    gap: 8,
    paddingRight: 8,
  },
  chip: {
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "transparent",
    justifyContent: "center",
  },
  chipActive: {
    backgroundColor: "#E8F5E9",
    borderColor: Colors.primary,
  },
  chipText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.textSecondary,
  },
  chipTextActive: {
    color: Colors.primary,
  },
  primaryBtn: {
    backgroundColor: Colors.primary,
    minHeight: 48,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
  primaryBtnText: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryBtn: {
    borderWidth: 1.5,
    borderColor: Colors.primary,
    minHeight: 46,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
    backgroundColor: Colors.surface,
  },
  secondaryBtnText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: "800",
  },
  listRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: 10,
  },
  listMeta: {
    flex: 1,
  },
  listTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.text,
  },
  listSub: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  noteText: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 3,
  },
  stockText: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: "700",
    marginTop: 5,
  },
  lowStockText: {
    color: Colors.tertiary,
  },
  smallBtn: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
  },
  smallBtnActive: {
    borderColor: Colors.primary,
    backgroundColor: "#E8F5E9",
  },
  smallBtnText: {
    fontSize: 12,
    fontWeight: "800",
    color: Colors.textSecondary,
  },
  smallBtnTextActive: {
    color: Colors.primary,
  },
  linkText: {
    fontSize: 12,
    fontWeight: "800",
    color: Colors.primary,
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textSecondary,
    paddingVertical: 10,
  },
  helperText: {
    marginTop: 6,
    fontSize: 11,
    color: Colors.textSecondary,
  },
  fieldErrorText: {
    color: Colors.tertiary,
    fontSize: 11,
    marginTop: 4,
    fontWeight: "600",
  },
  ledgerNumbers: {
    alignItems: "flex-end",
    minWidth: 92,
  },
  ledgerIn: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: "800",
  },
  ledgerOut: {
    fontSize: 12,
    color: Colors.tertiary,
    fontWeight: "800",
    marginTop: 2,
  },
  ledgerBalance: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  amountText: {
    fontSize: 13,
    fontWeight: "800",
    color: Colors.text,
  },
});