export const API_ROLE_VALUES = ["OWNER", "ACCOUNTS", "SUPERVISOR", "FARMER"] as const;
export const API_USER_STATUS_VALUES = ["ACTIVE", "INVITED", "DISABLED"] as const;

export const API_FARM_STATUS_VALUES = ["ACTIVE", "INACTIVE"] as const;
export const API_BATCH_STATUS_VALUES = [
  "ACTIVE",
  "CANCELLED",
  "PLANNED",
  "SALES_RUNNING",
  "SETTLEMENT_PENDING",
  "CLOSED",
] as const;
export const API_SALE_STATUS_VALUES = ["CANCELLED", "DRAFT", "CONFIRMED"] as const;
export const API_TREATMENT_KIND_VALUES = ["OTHER", "VACCINATION", "MEDICATION"] as const;

export const API_EXPENSE_CATEGORY_CODE_VALUES = [
  "CHICKS",
  "FEED",
  "MEDICINE",
  "VACCINE",
  "TRANSPORT",
  "OFFICE_EXPENSE",
  "SUPERVISOR_EXPENSE",
  "OTHER_COMPANY",
  "ELECTRICITY",
  "COCO_PITH",
  "LABOUR",
  "WATER",
  "DIESEL",
  "SHED_MAINTENANCE",
  "REPAIRS",
  "MISCELLANEOUS",
  "OTHER_FARMER",
] as const;
export const API_COMPANY_EXPENSE_CATEGORY_CODE_VALUES = [
  "CHICKS",
  "FEED",
  "MEDICINE",
  "VACCINE",
  "TRANSPORT",
  "OFFICE_EXPENSE",
  "SUPERVISOR_EXPENSE",
  "OTHER_COMPANY",
] as const;
export const API_FARMER_EXPENSE_CATEGORY_CODE_VALUES = [
  "ELECTRICITY",
  "COCO_PITH",
  "LABOUR",
  "WATER",
  "DIESEL",
  "SHED_MAINTENANCE",
  "REPAIRS",
  "MISCELLANEOUS",
  "OTHER_FARMER",
] as const;
export const API_EXPENSE_LEDGER_VALUES = ["FARMER", "COMPANY"] as const;
export const API_EXPENSE_APPROVAL_STATUS_VALUES = ["PENDING", "APPROVED", "REJECTED"] as const;

export const API_TRANSACTION_PAYMENT_STATUS_VALUES = ["CANCELLED", "PENDING", "PARTIAL", "PAID"] as const;
export const API_OPEN_TRANSACTION_PAYMENT_STATUS_VALUES = ["PENDING", "PARTIAL", "PAID"] as const;
export const API_PAYMENT_STATUS_VALUES = [
  "EXPIRED",
  "PENDING",
  "SUBMITTED",
  "APPROVED",
  "REJECTED",
] as const;
export const API_PAYMENT_DIRECTION_VALUES = ["INBOUND", "OUTBOUND"] as const;
export const API_PAYMENT_ENTRY_TYPE_VALUES = [
  "OTHER",
  "PURCHASE",
  "EXPENSE",
  "SALE_RECEIPT",
  "SETTLEMENT",
  "INVESTMENT",
] as const;

export const API_INVENTORY_MOVEMENT_TYPE_VALUES = ["PURCHASE", "ALLOCATION", "ADJUSTMENT", "RETURN"] as const;
export const API_PURCHASE_TYPE_VALUES = ["CHICKS", "FEED", "MEDICINE", "VACCINE", "EQUIPMENT", "OTHER"] as const;
export const API_CATALOG_ITEM_TYPE_VALUES = API_PURCHASE_TYPE_VALUES;
export const API_FINANCE_ENTRY_TYPE_VALUES = ["INVESTMENT", "OTHER_INCOME", "OTHER_EXPENSE"] as const;

export const API_PAYOUT_UNIT_VALUES = ["PER_BIRD_PLACED", "PER_BIRD_SOLD", "PER_KG_SOLD"] as const;
export const API_SETTLEMENT_STATUS_VALUES = ["DRAFT", "FINALIZED"] as const;
export const API_COMMENT_TARGET_TYPE_VALUES = [
  "PURCHASE",
  "SETTLEMENT",
  "FARM",
  "BATCH",
  "DAILY_LOG",
  "TREATMENT",
  "COST",
  "SALE",
  "PAYMENT",
] as const;

export const API_NOTIFICATION_TYPE_VALUES = [
  "MORTALITY_ALERT",
  "FEED_ALERT",
  "VACCINE_DUE",
  "FCR_ALERT",
  "PENDING_ENTRY",
  "SALES_READY",
  "PAYMENT_DUE",
  "GENERAL",
] as const;
export const API_NOTIFICATION_SEVERITY_VALUES = ["INFO", "WARNING", "CRITICAL"] as const;

export const API_SUBSCRIPTION_STATUS_VALUES = [
  "ACTIVE",
  "TRIAL",
  "GRACE",
  "EXPIRED",
  "PENDING_APPROVAL",
  "CANCELLED",
] as const;
