import { StyleSheet } from 'react-native';
const THEME_GREEN = '#0B5C36';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  header: {
    backgroundColor: THEME_GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  backBtn: {
    marginRight: 16,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    color: '#FFF',
    fontWeight: '600',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerIcon: {
    padding: 2,
  },
  heroBox: {
    backgroundColor: '#FFF',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
  },
  statusBadge: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  statusText: {
    color: THEME_GREEN,
    fontSize: 12,
    fontWeight: '700',
  },
  heroFarm: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4B5563',
    marginTop: 6,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  heroMetaText: {
    fontSize: 12,
    color: '#111827',
    fontWeight: '700',
  },
  heroMetaDivider: {
    marginHorizontal: 10,
    color: '#D1D5DB',
  },
  tabsWrapper: {
    backgroundColor: '#FFF',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tabsScroll: {
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  tabBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  tabBtnActive: {
    backgroundColor: THEME_GREEN,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7280',
  },
  tabTextActive: {
    color: '#FFF',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 12,
  },
  viewAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: THEME_GREEN,

  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridCard: {
    width: '48.5%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  gridCardIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridCardTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  gridVal: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    lineHeight: 18,
    marginTop: 2,
  },
  gridLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    lineHeight: 14,
  },
  chartCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 16,
    marginBottom: 20,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4B5563',
  },
  chartBox: {
    flexDirection: 'row',
    height: 140,
  },
  yAxisLabelsLeft: {
    justifyContent: 'space-between',
    paddingRight: 8,
  },
  yAxisLabelsRight: {
    justifyContent: 'space-between',
    paddingLeft: 8,
  },
  yText: {
    fontSize: 10,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  chartArea: {
    flex: 1,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  gridLine: {
    height: 1,
    backgroundColor: '#F3F4F6',
    width: '100%',
  },
  mockPathGreen: {
    position: 'absolute',
    bottom: 40,
    left: -10,
    width: '120%',
    height: 40,
    borderTopWidth: 2,
    borderColor: '#10B981',
    borderRadius: 40,
    transform: [{ rotate: '-5deg' }],
  },
  mockPathRed: {
    position: 'absolute',
    top: 30,
    left: -10,
    width: '120%',
    height: 50,
    borderBottomWidth: 2,
    borderColor: '#EF4444',
    borderRadius: 50,
    transform: [{ rotate: '10deg' }],
  },
  xAxisLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 24,
  },
  xText: {
    fontSize: 10,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 14,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  activityIconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityBody: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  activityTime: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  activityAuthor: {
    fontSize: 12,
    fontWeight: '700',
    color: '#111827',
  },
  emptyStateCard: {
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 24,
  },
  emptyStateTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
    marginTop: 10,
  },
  emptyStateText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 4,
    textAlign: 'center',
  },
  dailyLogCard: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 12,
  },
  dailyLogHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dailyLogDate: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
  },
  dailyLogSub: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 3,
  },
  editBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#ECFDF5',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  editBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: THEME_GREEN,
  },
  dailyMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  dailyMetricCard: {
    width: '31%',
    minHeight: 62,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  dailyMetricValue: {
    fontSize: 14,
    fontWeight: '800',
  },
  dailyMetricLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#6B7280',
    marginTop: 3,
  },
  dailyNotes: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4B5563',
    marginTop: 12,
    lineHeight: 18,
  },
  expenseHistoryCard: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 12,
  },
  expenseHistoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  expenseHistoryTitleWrap: {
    flex: 1,
  },
  expenseHistoryTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
  },
  expenseHistoryMeta: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 3,
  },
  expenseHistoryAmount: {
    fontSize: 15,
    fontWeight: '900',
    color: THEME_GREEN,
  },
  expenseInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoPill: {
    minWidth: '31%',
    maxWidth: '48%',
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 9,
  },
  infoPillLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#9CA3AF',
    marginBottom: 2,
  },
  infoPillValue: {
    fontSize: 12,
    fontWeight: '800',
    color: '#374151',
  },
  auditRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  auditItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    maxWidth: '100%',
  },
  auditText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4B5563',
    flexShrink: 1,
  },
  expenseNotes: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4B5563',
    marginTop: 12,
    lineHeight: 18,
  },
  billButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    backgroundColor: '#ECFDF5',
    paddingVertical: 10,
    marginTop: 12,
  },
  billButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: THEME_GREEN,
  },
  expenseCompactRow: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 9,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  expenseCompactMain: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  expenseCompactIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  expenseCompactContent: {
    flex: 1,
    minWidth: 0,
  },
  expenseCompactTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  expenseCompactTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '800',
    color: '#111827',
  },
  expenseCompactAmount: {
    flexShrink: 0,
    fontSize: 13,
    fontWeight: '900',
    color: THEME_GREEN,
  },
  expenseCompactMeta: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6B7280',
    marginTop: 2,
  },
  expenseCompactDetail: {
    fontSize: 10,
    fontWeight: '700',
    color: '#6B7280',
    marginTop: 3,
  },
  expenseCompactNotes: {
    fontSize: 10,
    fontWeight: '700',
    color: '#374151',
    marginTop: 3,
  },
  expenseCompactAction: {
    width: 26,
    height: 26,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  salesSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  salesAdjustments: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
    gap: 4,
  },
  adjustmentText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4B5563',
  },
  commentCard: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 12,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  commentIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  commentTitleWrap: {
    flex: 1,
  },
  commentTarget: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  commentDate: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 2,
  },
  commentText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    lineHeight: 20,
  },
  correctionBox: {
    backgroundColor: '#FFF7ED',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FED7AA',
    padding: 10,
    marginTop: 12,
  },
  correctionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#EA580C',
    marginBottom: 4,
  },
  correctionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7C2D12',
    lineHeight: 18,
  },
  commentMetaRow: {
    marginTop: 12,
    gap: 4,
  },
  commentMetaText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  expenseToggleBox: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  expenseToggleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 6,
  },
  expenseToggleBtnActive: {
    backgroundColor: THEME_GREEN,
  },
  expenseToggleText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4B5563',
  },
  expenseToggleTextActive: {
    color: '#FFF',
  },
  expenseSummaryCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 24,
    overflow: 'hidden',
  },
  expenseSummaryHeader: {
    backgroundColor: '#F0FDF4',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  expenseSummaryTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME_GREEN,
  },
  expenseSummaryBody: {
    padding: 16,
  },
  expenseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  expenseRowLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4B5563',
  },
  expenseRowSub: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  expenseTotalVal: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  pnlEmphasisLabel: {
    color: THEME_GREEN,
    fontWeight: '800',
  },
  pnlEmphasisValue: {
    fontSize: 18,
  },
  expenseDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 12,
  },
  addExpenseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addExpenseText: {
    fontSize: 14,
    fontWeight: '700',
    color: THEME_GREEN,
  },
  expenseTable: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    marginBottom: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tableColTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#111827',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  tableColText: {
    fontSize: 13,
    color: '#111827',
    fontWeight: '600',
  },
  tableFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  tableFooterLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME_GREEN,
  },
  tableFooterVal: {
    fontSize: 16,
    fontWeight: '800',
    color: THEME_GREEN,
  },
  noteBox: {
    backgroundColor: '#EFF6FF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  noteText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
    textAlign: 'center',
  },
  farmerPnlCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FED7AA',
    marginBottom: 24,
    overflow: 'hidden',
  },
  farmerPnlHeader: {
    backgroundColor: '#FFF7ED',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#FED7AA',
  },
  farmerPnlTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#EA580C',
  },
  dailyLogCardPremium: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 14,
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
    shadowColor: "#1E293B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  dateBadge: {
    width: 52,
    height: 58,
    borderRadius: 10,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  dateBadgeBody: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  dateBadgeMonth: {
    fontSize: 9,
    fontWeight: "900",
    color: "#0B5C36",
    lineHeight: 11,
    textAlign: "center",
    width: "100%",
  },
  dateBadgeDay: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1E293B",
    lineHeight: 20,
    textAlign: "center",
    width: "100%",
  },
  dateBadgeWeekday: {
    fontSize: 8,
    fontWeight: "800",
    color: "#64748B",
    lineHeight: 10,
    textAlign: "center",
    width: "100%",
  },
  cardContent: {
    flex: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  batchCodeTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1E293B",
  },
  cardActionGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  iconActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  editButtonIcon: {
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  editButtonText: {
    fontSize: 11,
    fontWeight: "900",
    color: THEME_GREEN,
  },
  dividerLine: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginVertical: 10,
  },
  alertRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginVertical: 4,
  },
  alertPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  alertPillRed: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FEE2E2",
  },
  alertPillOrange: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FFEDD5",
  },
  alertTextRed: {
    fontSize: 11,
    fontWeight: "800",
    color: "#DC2626",
  },
  alertTextOrange: {
    fontSize: 11,
    fontWeight: "800",
    color: "#D97706",
  },
  opsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 6,
    gap: 8,
  },
  opsItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  opsIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  opsTextWrap: {
    flex: 1,
  },
  opsLabel: {
    fontSize: 9,
    color: "#64748B",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  opsValue: {
    fontSize: 12,
    color: "#0F172A",
    fontWeight: "800",
    marginTop: 1,
  },
  notesContainer: {
    flexDirection: "row",
    backgroundColor: "#F8FAFC",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 8,
    gap: 6,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  notesText: {
    flex: 1,
    color: "#475569",
    fontSize: 11,
    fontWeight: "600",
  },
  treatmentChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  treatmentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F1F5F9",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  treatmentChipText: {
    color: "#475569",
    fontSize: 10,
    fontWeight: "800",
  },
  detailBox: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    gap: 12,
  },
  detailGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  detailGridCard: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 10,
    alignItems: "center",
  },
  detailLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#64748B",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 11,
    fontWeight: "800",
    color: "#1E293B",
    textAlign: "center",
  },
  detailNotesBox: {
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 10,
    gap: 4,
  },
  detailSectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#0F172A",
    textTransform: "uppercase",
  },
  detailNotesVal: {
    fontSize: 11,
    color: "#475569",
    fontWeight: "600",
    lineHeight: 16,
  },
  detailTreatmentsBox: {
    gap: 8,
  },
  detailTreatmentCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderLeftWidth: 4,
    padding: 10,
    gap: 4,
  },
  detailTreatmentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  detailTreatmentKind: {
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  detailTreatmentBirds: {
    fontSize: 10,
    fontWeight: "800",
    color: "#475569",
  },
  detailTreatmentName: {
    fontSize: 12,
    fontWeight: "800",
    color: "#1E293B",
  },
  detailTreatmentMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  detailTreatmentMetaVal: {
    fontSize: 10,
    fontWeight: "600",
    color: "#64748B",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "85%",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalHeaderLeft: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0F172A",
  },
  modalSubtitle: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "600",
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  modalScrollContent: {
    paddingBottom: 24,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginVertical: 14,
  },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    paddingBottom: 10,
  },
  modalCancelBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  modalCancelBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#475569",
  },
  modalSubmitBtn: {
    flex: 2,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#0B5C36",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  modalSubmitBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  mstFlockBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  mstFlockItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mstDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
  },
  statusTagText: {
    fontSize: 12,
    fontWeight: "700",
  },
  dateBadgePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#E7F5ED",
    borderWidth: 1,
    borderColor: "#CBE6D5",
    marginLeft: 10,
    alignSelf: 'center',
  },
  dateBadgePillText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#0B5C36",
  },
  mstOpsBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#F1F5F9",
    borderRadius: 14,
    paddingVertical: 14,
    marginVertical: 16,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  mstOpsCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  mstOpsVal: {
    fontSize: 22,
    fontWeight: "900",
  },
  mstOpsUnit: {
    fontSize: 13,
    fontWeight: "800",
    color: "#64748B",
  },
  mstOpsLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#64748B",
    textTransform: "uppercase",
    marginTop: 3,
    letterSpacing: 0.5,
  },
  mstOpsDivider: {
    width: 1,
    height: 32,
    backgroundColor: "#E2E8F0",
  },
  mstRemarksBox: {
    backgroundColor: "#F0FDF4",
    borderLeftWidth: 4,
    borderLeftColor: "#0B5C36",
    borderRadius: 10,
    padding: 14,
    marginVertical: 14,
    borderWidth: 1,
    borderColor: "#DCFCE7",
  },
  mstRemarksHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  mstRemarksTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#0B5C36",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mstRemarksText: {
    fontSize: 13,
    fontStyle: "italic",
    color: "#0B5C36",
    lineHeight: 18,
  },
  mstTreatmentSection: {
    marginVertical: 12,
  },
  mstSectionTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: "#64748B",
    textTransform: "uppercase",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  mstTimelineContainer: {
    marginTop: 8,
  },
  mstTimelineItem: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  mstTimelineLeft: {
    alignItems: "center",
    width: 14,
  },
  mstTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 14,
  },
  mstTimelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#E2E8F0",
    marginTop: 6,
    marginBottom: -16,
  },
  mstTimelineRightCard: {
    flex: 1,
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderLeftWidth: 4,
    borderRadius: 12,
    padding: 12,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.01,
    shadowRadius: 4,
    elevation: 1,
    gap: 2,
  },
  mstTimelineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  mstTimelineKind: {
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  mstTimelineBirds: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: "600",
  },
  mstTimelineName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0F172A",
  },
  mstTimelineDetail: {
    fontSize: 12,
    color: "#64748B",
    fontWeight: "600",
  },
  simpleDetailsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  simpleDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  simpleDetailLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748B',
  },
  simpleDetailValue: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1E293B',
  },
  simpleDetailNotesText: {
    fontSize: 13,
    color: '#334155',
    marginTop: 4,
    lineHeight: 18,
  },
  simpleTreatmentRow: {
    paddingVertical: 6,
  },
  simpleTreatmentText: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
  },
  simpleTreatmentNotes: {
    fontSize: 12,
    color: '#64748B',
    paddingLeft: 10,
    marginTop: 2,
  },
});
